version: '3'
services:
    web:
        image: gcr.io/${GCLOUD_PROJECT_ID}/${GCLOUD_APP_NAME}:latest
        build: .
        ports:
            - '80:${PORT}'
        environment:
            - NODE_ENV=${NODE_ENV}
            - GCLOUD_PROJECT_ID=${GCLOUD_PROJECT_ID}
            - AQI_CN_URL=${AQI_CN_URL}
            - AQI_CN_TOKEN=${AQI_CN_TOKEN}
            - DEFAULT_LOCATION_NAME=${DEFAULT_LOCATION_NAME}
            - NOTIFY_ONLY_UNHEALTHY=${NOTIFY_ONLY_UNHEALTHY}
            - API_KEY=${API_KEY}
            - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
            - PORT=${PORT}
            - PRIVATE_KEY=${PRIVATE_KEY}
