version: '3'
services:
  web:
    build: .
    ports:
      - "80:${PORT}"
    environment:
      - AQI_CN_URL=${AQI_CN_URL}
      - AQI_CN_TOKEN=${AQI_CN_TOKEN}
      - DEFAULT_LOCATION_NAME=${DEFAULT_LOCATION_NAME}
      - LINE_NOTIFY_ACCESS_TOKEN=${LINE_NOTIFY_ACCESS_TOKEN}
      - LINE_NOTIFY_BASE_URL=${LINE_NOTIFY_BASE_URL}
      - NOTIFY_ONLY_UNHEALTHY=${NOTIFY_ONLY_UNHEALTHY}
      - TMD_UID=${TMD_UID}
      - TMD_API_KEY=${TMD_API_KEY}
      - PORT=${PORT}